# -*- coding: utf-8 -*-
"""WeatherHistory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jd5nd3_JsoiMHnMnkD5Xg-KbMPmqr9ti
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

#Data Loading

data=pd.read_csv("/content/weatherHistory.csv")
print(data.head())

data.tail()

data["Precip Type"].value_counts()

data.info()

data.describe()

data.shape

data.columns

data.isnull().sum()

data.dropna()

import matplotlib.pyplot as plt

#line plot
plt.plot(data["Temperature (C)"])
plt.title("Line Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()

data["Precip Type"].value_counts().plot(kind="bar")
plt.title("Bar Plot")
plt.xlabel("Precip Type")
plt.ylabel("Count")
plt.show()

data["Precip Type"].value_counts().plot(kind="pie",autopct="%0.1f%%")
plt.title("Pie chart")
plt.show()

import seaborn as sns

sns.histplot(data['Temperature (C)'])
plt.show()

sns.violinplot(x="Precip Type",y="Temperature (C)",data=data)
plt.show()

sns.countplot(x="Precip Type",data=data)
plt.show()

#Creation of new columns
data["AreaCm"]=data["Temperature (C)"] * data["Humidity"]
data.head()

#Binning categories by bin
data["CmGroup"]=pd.cut(data["Temperature (C)"],bins=[0,2.5,5,7],labels=["Small","Medium","Large"])
data.head()

data['CmGroup'].value_counts()

#encoding
#1. Label Encoding categorical value into numerical value
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Precip Type_encoded']=le.fit_transform(data['Precip Type'])
print(data.head)

print(data.head())

#Feature scaling ( Standardization )
# z=(x-mean/std) scaler

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
# Selecting only numerical columns for scaling
scaled_data=scaler.fit_transform(data[['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)']])

data_scaled=pd.DataFrame(scaled_data,columns=['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)'])
print(data_scaled.head())

#Feature Scaling (min-max scaling) 0 to 1 positive value
# x_new = (x_old - x_min)/(x_max - x_min)

from sklearn.preprocessing import MinMaxScaler

m=MinMaxScaler()
numerical_cols = ['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)']
m_scaled=m.fit_transform(data[numerical_cols])

data_minmax=pd.DataFrame(m_scaled,columns=numerical_cols)
print(data_minmax.head())

#Polynomial Features

from sklearn.preprocessing import PolynomialFeatures

pol=PolynomialFeatures(degree=2)
# Select only numerical columns for polynomial features
numerical_features_for_poly = ['Temperature (C)', 'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)']
pol_features=pol.fit_transform(data[numerical_features_for_poly])

data_pol=pd.DataFrame(pol_features, columns=pol.get_feature_names_out(numerical_features_for_poly))
data_pol.head()